In [1]:
import numpy as np

a = "Ready"
one = 1
two = 2
three = 3
four = 4
five = 5
six = 6
seven = 7
eight = 8
nine = 9
space_taken = "That space is already taken, please choose another space"
win = False
aiTurn = 0
threat = 0
randList = [one,seven]
Answer = input("Enter Ready to start")
hOne = [one,two,three]
hTwo = [four,five,six]
hThree = [seven, eight, nine]
vOne = [one, four, seven]
vTwo = [two, five, eight]
vThree = [three, six, nine,]
diagOne = [one, five, nine]
diagTwo = [seven, five, three]
arr = np.array([hOne, hTwo, hThree])
allNums = [one,two,three, four, five, six, seven, eight, nine]
bestChoice = [five, one, seven]
test = 0
best = -1
dThreat1 = 0
dThreat2 = 0
aiWc = 0
pWc = 0
tieC = 0
diag1aiWc = 0
diag2aiWc = 0
diag1pWc = 0
diag2pWc = 0
v = 3
firstTurn = True
stoopid = False
wC = 0
diag1wC = 0
diag2wC = 0
while a != Answer :
  Answer = input("Please Enter Ready to Start")
if a == Answer:
  while win == 0:
    for lists in arr:
      print(lists)
    try:
      place = int(input("Choose a number(Use arabic numerals 1,5 etc.)"))
    except:
      print("That isn't an applicable number, Try again")
      stoopid = True
      aiTurn = 1
    threat = 0
    if stoopid == False:
      for i in range(0,len(arr)):
        for num in range(0, len(arr[i])):
          #print(arr[i,num], "test")
          #print(arr)
          if place == arr[i,num]:
            #print("Yeet")
            if arr[i,num] != test and arr[i, num] != best:
              arr[i,num] = test
              aiTurn = 1
              #print("Yote")
    if aiTurn != 1:
      print("That is not an applicable number or space, please choose another space.")

    #AI's Turn
    if firstTurn == True:
      #print("first turn runs")
      for p in bestChoice:
        if firstTurn == True:
          for i in range(0,len(arr)):
            for num in range(0, len(arr[i])):
              if p == arr[i,num]:
               if arr[i, num] != test and arr[i,num] != best :
                  arr[i,num] = best
                  aiTurn = 0
                  firstTurn = False
                  #print("First Turn does something")
  #Attempting to win
    if aiTurn == 1:
      #print("Side WC Runs")
      for i in range(0,len(arr)):
        for num in range(0, len(arr [i])):
          if arr[i,num] == -1:
            wC = wC + 1
            #print(threat, i)
            if wC == 2:
              for num in range(0, len(arr[i])):
                if arr[i, num] != best and arr[i, num]:
                  arr[i,num] = -1
                  aiTurn = 0
                  #print("Side does something")
                  wC = 0
        wC = 0
    if aiTurn == 1:
      #print("Vert wC Runs")
      v = 3
      diag1wC = 0
      diag2wC = 0
      for r in range(0, 3):
        v += -1
        for i in range(0,len(arr)):
          if arr[i,r] == -1:
            wC = wC + 1
            if wC == 2:
              for i in range(0, len(arr)):
                if arr[i,r] != 0 and arr[i, r] != -1:
                  print("Vert wC does something")
                  print(arr[i,r])
                  arr[i,r] = best
                  aiTurn = 0
                  firstTurn = False
                  wC = 0
        wC = 0
        if aiTurn == 1:
          #print(arr[r,r], "Current Num")
          #print(diag1wC, "")
          if arr[r,r] == best:
            diag1wC += 1
            #print("diagwC1:", diag1wC)
            if diag1wC == 2:
              #print("Diag wC 1 Runs")
              for r in range(0, 3):
                if arr[r, r] != best and arr[r,r] != test:
                  arr[r,r] = best
                  aiTurn = 0
                  firstTurn = False
                  #print("Diag WC 1 does something")
                  diag1wC = 0
        #print("arr[r,v]:", arr[r,v] )
        if aiTurn == 1: 
          if arr[r,v] == -1:
            #print("DiagwC2 runs")
            diag2wC += 1
            if diag2wC == 2:
              v = 3
              for r in range(0, 3):
                v += -1
                if arr[r, v] != best and arr[r,v] != test:
                  arr[r,v] = -1
                  aiTurn = 0
                  firstTurn = False
                  diag2wC = 0
                  #print("Diag wC 2 does something")
  #Not losing
    if aiTurn == 1:
      #print("Side Runs")
      for i in range(0,len(arr)):
        for num in range(0, len(arr[i])):
          if arr[i,num] == -1:
            threat = threat - 1
          elif arr[i,num] == 0:
            threat = threat+1
            #print(threat, i)
          if threat == 2:
            for num in range(0, len(arr[i])):
              if arr[i,num] != test and arr[i, num] != best:
                arr[i,num] = -1
                aiTurn = 0
                #print("Side does something")
                threat = 0
        threat = 0
    if aiTurn == 1:
      #print("Vert Threat Runs")
      v = 3
      for r in range(0, 3):
        v += -1
        #print("V:", v)
        for i in range(0,len(arr)):
          #print(arr[i,r])
          #print(num)
          if arr[i,r] == -1:
            threat = threat - 1
          elif arr[i,r] == 0:
            threat = threat+1
            #print(threat, i)
          if threat == 2:
            for i in range(0, len(arr)):
              if arr[i,r] != test and arr[i, num] != best:
                #print("Vert does something")
                arr[i,r] = -1
                aiTurn = 0
                firstTurn = False
                threat = 0
        threat = 0
        if aiTurn == 1:
          if arr[r,r] == -1:
            dThreat1 += -1
          elif arr[r,r] == 0:
            #print("Diag 1 Runs")
            dThreat1 +=1
            if dThreat1 == 2:
              for r in range(0, 3):
                if arr[r,r] != 0 and arr[r, r] != best:
                  arr[r,r] = -1
                  aiTurn = 0
                  firstTurn = False
                  #print("Diag 1 does something")
       # print("arr[r,v]:", arr[r,v] )
        if aiTurn == 1:
          if arr[r,v] == -1:
            dThreat2 += -1  
          elif arr[r,v] == 0:
            dThreat2 += 1
            if dThreat2 == 2:
              v = 3
              for r in range(0, 3):
                v += -1
                if arr[r,v] != 0 and arr[i, num] != best:
                  arr[r,v] = -1
                  aiTurn = 0
                  firstTurn = False
                  #print("Diag 2 does something")
                  dThreat2 = 0
    if aiTurn == 1: 
      #print("ELSE Runs")
      for stuff in allNums:
        if aiTurn == 1:
          #print(stuff)
          for i in range(0,len(arr)):
            for num in range(0, len(arr[i])):
              if stuff == arr[i,num]:
                if arr[i,num] != 0 and arr[i,num] != -1:
                  arr[i, num] = best
                  aiTurn = 0
                  #print("random/else does something")
    if aiTurn == 1:
      #This is to make sure nothing happens after board capsizing
      aiTurn = 0
    #winchecker
    for i in range(0,len(arr)):
      pWc = 0
      aiWc = 0
      for num in range(0, len(arr [i])):
        if arr[i,num] == 0:
          pWc +=1
          tieC +=1
          #print("Hori pWC:",pWc)
        elif arr[i, num] == -1:
          aiWc +=1
          tieC += 1
    if pWc == 3:
      win = True
      print("Congrats, Please change everything you messed with back", "HoriWin")
    elif aiWc == 3:
      win = True
      print("You Lose!")
    elif tieC == 9:
      win = True
      print("You Capsized the Board!")
    pWc = 0
    tieC = 0
    aiWc = 0  
    
    v = 3
    diag1aiWc = 0
    diag2aiWc = 0
    diag1pWc = 0
    diag2pWc = 0
    for r in range(0, 3):
      v += -1
      pWc = 0
      aiWc = 0
      for i in range(0,len(arr)):
        if arr[i,r] == -1:
          aiWc +=1
          tieC += 1
        elif arr[i,r] == 0:
          pWc +=1
          tieC += 1
      if pWc == 3:
        win = True
        print("Congrats, Please change everything you messed with back", "Vert Win")
      elif aiWc == 3:
        win = True
        print("You Lose!")
      elif tieC == 9:
        win = True
        print("You Capsized the Board!")
      pWc = 0
      tieC = 0
      aiWc = 0  

      #print(arr[r,r], "currentNum")
      if arr[r,r] == -1:
        #print(diag1aiWc, "Before")
        diag1aiWc += 1
        tieC += 1
        #print("increment")
        #print(diag1aiWc, "after")
      elif arr[r,r] == 0:
        diag1pWc +=1
        tieC += 1
      if diag1pWc == 3:
        win = True
        print("Congrats, Please change everything you messed with back", "Diag1Win")
      elif diag1aiWc == 3:
        win = True
        print("You Lose!")
      elif tieC == 9:
        win = True
        print("You Capsized the Board!")
      #print(diag1aiWc, "diag1aiWc")

    if arr[r,v] == -1:
      diag2aiWc +=1
      tieC += 1
    elif arr[r,v] == 0:
      diag2pWc +=1
      tieC += 1
    if diag2pWc == 3:
      win = True
      print("Congrats, Please change everything you messed with back", "Diag2Win")
    elif diag2aiWc == 3:
      win = True
      print("You Lose!")
    elif tieC == 9:
      win = True
      print("You Capsized the Board!")
    pWc = 0
    tieC = 0
    aiWc = 0  

  if win == True:
    for lists in arr:
      print(lists)

Enter Ready to startReady
[1 2 3]
[4 5 6]
[7 8 9]
Choose a number(Use arabic numerals 1,5 etc.)2
[1 0 3]
[ 4 -1  6]
[7 8 9]
Choose a number(Use arabic numerals 1,5 etc.)3
[-1  0  0]
[ 4 -1  6]
[7 8 9]
Choose a number(Use arabic numerals 1,5 etc.)9
[-1  0  0]
[ 4 -1 -1]
[7 8 0]
Choose a number(Use arabic numerals 1,5 etc.)4
[-1  0  0]
[ 0 -1 -1]
[-1  8  0]
Choose a number(Use arabic numerals 1,5 etc.)8
You Capsized the Board!
[-1  0  0]
[ 0 -1 -1]
[-1  0  0]
